enforce_secure_profile: false
listeners:
- query_port: 25585
  motd: \u00a72\u00a7l[1.18.2]\u00a7r New Educational Experiences - \u00a73CITM \u00a7r-
    \u00a76\u00a7lTelmo Beroiz
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25585
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - slashserver.application-1
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - slashserver.application-1
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
prevent_proxy_connections: false
ip_forward: true
groups:
  Telmiyo:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 909e6ca1-7dd2-4325-aba5-b1d50cbf186a
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: New Educational Experiences - CITM - Telmo Beroiz
    address: localhost:25599
    restricted: false
  application-1:
    motd: '&1Application 01 - Jobs'
    address: localhost:25525
    restricted: false
